[pytest]
testpaths =
    lavrentiy_pkg/tests
    tests
python_files = test_*.py
norecursedirs =
    build
    build-native
    build-onedir
    dist
    dist-native
    dist-onedir
    eval-build
    local
